### ISSUE TITLE
ctd, release3 branch, error during import

### ISSUE THREAD

**Issue by theoryno3** [bio2rdf/bio2rdf-scripts#333]
For all of the ctd tables that have been processed, the virtuoso server complains about a syntax error. I believe the error lies with the url's having one front-slash instead of two. 

```
eg, <http:/bio2rdf.org/ctd_vocabulary:abu> <http:/purl.org/dc/terms/identifier>
```

Below is one example for ctd_chem_gene_ixns.nq.

ctd_chem_gene_ixn_types.nq.gz
ctd_chem_go_enriched.nq.gz
ctd_chemicals_diseases.nq.gz
ctd_chemicals.nq.gz
ctd_chem_pathways_enriched.nq.gz
ctd_diseases.nq.gz
ctd_diseases_pathways.nq.gz
ctd_genes_diseases.nq.gz
ctd_genes_pathways.nq.gz
ctd_pathways.nq.gz

```
Connected to OpenLink Virtuoso
Driver: 07.00.3203 OpenLink Virtuoso ODBC Driver
OpenLink Interactive SQL (Virtuoso), version 0.9849b.
Type HELP; for help and EXIT; to exit.
*** Error 22007: [Virtuoso Driver][Virtuoso Server]XM033: XML parser detected an error:
    ERROR  : Syntax error in the attribute list (no whitespace)
at line 1 column 9 of source text
<http:/bio2rdf.org/ctd_resource:C1122973784> <http:/purl.org/dc/terms/identi
  ------^
at line 0 of Top-Level:
DB.DBA.RDF_LOAD_RDFXML_MT(file_to_string_output ('/home/bio2rdf/rdf/ctd/2/ctd_chem_gene_ixns.nq'), '', 'http:/bio2rdf.org/ctd_chem_gene_ixns', 784, 16)
Done. -- 4977 msec.
```

**Comment by demeiyan** [comment]
Hi,I'm  encountering the error. How do you solve this  problem? @theoryno3 
XML parser detected an error:
ERROR: syntax error in the attribute list(no whitespace)

**Comment by micheldumontier** [comment]
Give me exactly what you run in the command line
