### ISSUE TITLE
federated SPARQL queries

### ISSUE THREAD

**Issue by gigster99** [bio2rdf/bio2rdf-scripts#408]
We're having a problem with federated SPARQL queries that access Bio2RDF.
For example, we have this SPARQL clause:

   { SERVICE <http://pubmed.bio2rdf.org/sparql> { SELECT ?title WHERE { <http://bio2rdf.org/pubmed:16572602> dcterms:title ?title. } } }

The federated query worked about a month ago but has failed since. Initially we thought the problem was related to a change in the SPARQL processor we use:

  http://www.sparql.org/sparql.html

But now we think that the above clause is failing, and therefore corrupting the complete query.

We also see that SPARQL queries on Bio2RDF are failing (https://github.com/bio2rdf/bio2rdf-scripts/wiki/Query-repository) because YASGUI is unreachable.

These may be 2 separate issues (our clause and YASGUI); or it may be that YASGUI is the physical end-point that processes a request to <http://pubmed.bio2rdf.org/sparql>.

Are there changes we should make to federated queries to properly access Bio2RDF data?

We have a number of queries in development that are intended to run against Bio2RDF, and we'd prefer not to use alternative endpoints (like alternative end-points to query PubMed).

**Comment by micheldumontier** [comment]
I'm sorry that you had trouble with Bio2RDF endpoints.  These are demonstrative service endpoints, and should not be used for production systems. Please email me at michel.dumontier@gmail.com to discuss options.
