### ISSUE TITLE
Add Kegg Pathway data to Bio2RDF

### ISSUE THREAD

**Issue by hansmeets** [bio2rdf/bio2rdf-scripts#420]
1. Download KGML files with pathway data
2. Parse KGML files to extract relations 
Take an example from map05218.kgml
<relation entry1="12" entry2="33" type="PPrel">
        <subtype name="activation" value="--&gt;"/>
    </relation>

The entries indicate compounds that are interacting with each other, specifically entry1 acting on entry2. PPrel indicates the kind of line connecting the two compounds, in this case a strong black line. The subtype here indicates the kind of activity of entry1 on entry2, in this case activation, with "--&gt" being the arrow symbol

3) Once we have the relations we iterate over them to save them into triples for RDF-ization. My untested solution for this task is as follows, within the iteration:

I am saving each field of the relation into variables that I subsequently save into an array; this array is an array of arrays with the third field of each indexed array being an array as well. The first two entries of each indexed array are entry1 and entry2, and the final entry is an array containing connection information. This is my first stab at triple-ization of the data.

**Comment by micheldumontier** [comment]
in 20ebe90431f42df76fd94787c2b3e297960eb9be
427743dfd4860e2b84e06241bb966ea7b89f8b0b
17738b2a00d62ba50fc0939fd71f15b7a2de3edb
