### ISSUE TITLE
PharmGKB Annotations RDF

### ISSUE THREAD

**Issue by maulikkamdar** [bio2rdf/bio2rdf-scripts#429]
There might be an error with the PharmGKB annotations RDFization - Some of the triples do not have valid URIs. Maybe these need to be SHA-1/MD5 hashed? 

**E.g. Line 121937**
`<http://bio2rdf.org/pharmgkb:","TT:Patients with metastasized cancer and the TT genotype may have improved response to capecitabine or fluorouracil as compared to people with the GT or GG genotype. Other genetic and clinical factors may also influence a patient's response to capecitabine and fluorouracil. Please note: the single statistically significant association was for a haplotype that included five SNPs (rs2289310 G>T; rs1047840 G>A; rs17431184 T>C; rs17160359 G>T; rs2236722 A>G) that distinguished the "non-responder" phenotype from the "responder" phenotype when using a logistic regression multivariate model."> <http://purl.org/dc/terms/identifier> "pharmgkb:\",\"TT:Patients with metastasized cancer and the TT genotype may have improved response to capecitabine or fluorouracil as compared to people with the GT or GG genotype. Other genetic and clinical factors may also influence a patient\'s response to capecitabine and fluorouracil. Please note: the single statistically significant association was for a haplotype that included five SNPs (rs2289310 G>T; rs1047840 G>A; rs17431184 T>C; rs17160359 G>T; rs2236722 A>G) that distinguished the \"non-responder\" phenotype from the \"responder\" phenotype when using a logistic regression multivariate model.\""^^<http://www.w3.org/2001/XMLSchema#string> <http://bio2rdf.org/pharmgkb_resource:bio2rdf.dataset.pharmgkb.R4> .`

**Comment by micheldumontier** [comment]
PharmGKB changes that format on a daily basis. lemme quickly look.

**Comment by micheldumontier** [comment]
fixed field value tokenizer - pharmgkb switched from semi colon to double quoted and comma delimited entries.
