### ISSUE TITLE
Kegg URI capitalization issues

### ISSUE THREAD

**Issue by maulikkamdar** [bio2rdf/bio2rdf-scripts#430]
There are two different capitalizations for a Kegg:Gene, causing problems while hopping between Kegg Genes, Drugs and Enzymes using Linked Data Fragments.
For e.g.

**(Kegg Enzyme)**
```
kegg:3.4.21.5 kegg_vocabulary:gene kegg:HSA_2147. 
```
**(Kegg Gene)**
```
kegg:hsa_2147 kegg_vocabulary:pathway kegg:map04610. 
```
**(Kegg Drug)**
```
kegg_resource:19b340fdfcb4dbca8b290c14e255d06e kegg_vocabulary:link kegg:HSA_2147 
```

**Comment by micheldumontier** [comment]
ok. that should do it.
