### ISSUE TITLE
Feature Request: GO Codes in Drugbank

### ISSUE THREAD

**Issue by maulikkamdar** [bio2rdf/bio2rdf-scripts#431]
Hi,

I was wondering if it was possible to have GO codes instead of simple text for Drugbank Triples. For example, currently the triples are the following:
```

drugbank:BE0000703 drugbank_vocabulary:go-function "ATPase activity".
drugbank:BE0000703 drugbank_vocabulary:go-component "membrane".
```

**Comment by micheldumontier** [comment]
Unless they have changed the source data (I made a request with no answer
by them), they have not been including the GO codes.

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by maulikkamdar** [comment]
Oh I see, the source code still has textual snippets. That is very inconvenient! 
It might be interesting to combine a version of the gene ontology to include additional triples post-RDFization indicating those GO codes (assuming naive string matching to GO terms works)

Thanks

**Comment by micheldumontier** [comment]
agreed. i certainly welcome contributions to the open source repository for
this :)

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by micheldumontier** [comment]
ok, i'm working on this.

**Comment by micheldumontier** [comment]
Fixed.
