### ISSUE TITLE
KEGG Target should "Link" to individual target entities

### ISSUE THREAD

**Issue by maulikkamdar** [bio2rdf/bio2rdf-scripts#432]
Hi,

I encountered the following triples indicating the Targets (CYP3A) of Cobicistat:

```
kegg:D09881 kegg_vocabulary:target kegg_resource:52292de0a46622a5ed543f7ab93393f8.
kegg_resource:52292de0a46622a5ed543f7ab93393f8 kegg_vocabulary:link kegg:HSA_1551 1576 1577 64816.
```

However, the link in the second triple is not traversable to retrieve information on the corresponding set of enzymes (which are different - CYP3A4, CYP3A5 etc.). 

I think the object in the second triple should be split into the corresponding enzyme URIs?

**Comment by maulikkamdar** [comment]
This actually creates a problem for SPARQL queries (at least using the Triple Pattern Fragments Server) because  `<http://bio2rdf.org/kegg:HSA_146 147 148>` is not considered a valid URI. 

On another note, I am surprised it did not raise a warning when I converted to HDT, because there was another case of the following triple `<http://bio2rdf.org/kegg_vocabulary:tRNA      T01001> <http://purl.org/dc/terms/identifier> "kegg_vocabulary:tRNA      T01001"`  where it shot an exception for the subject URI.

**Comment by micheldumontier** [comment]
ok. should work now. thanks for reporting all the errors!
