### ISSUE TITLE
Faulty PharmGKB triples

### ISSUE THREAD

**Issue by maulikkamdar** [bio2rdf/bio2rdf-scripts#434]
Hi,

There seems to be an ending "quote" for some triples in the PharmGKB Genes file. For example

`<http://bio2rdf.org/pharmgkb:PA195> <http://bio2rdf.org/pharmgkb_vocabulary:x-go> <http://bio2rdf.org/go:0030307\"> .`

**Comment by micheldumontier** [comment]
Fixed in issue #436
