### ISSUE TITLE
Hash URIs for Drugbank 

### ISSUE THREAD

**Issue by maulikkamdar** [bio2rdf/bio2rdf-scripts#445]
Hi,
I think it might be helpful to SHA1-Hash/MD5-Hash Drug Mixture labels before converting them to URIs. Currently some of the URIs are of the form 
- http://bio2rdf.org/drugbank_resource:Ac\uFFFD\uFFFDtaminoph\uFFFD\uFFFDne-500-Mg-Comprime
- http://bio2rdf.org/drugbank_resource:Rugby-Acetaminophen-500-Mg-And-Diphenhydramine-HCl-25-mg-Pain-Reliever/Sleep-Aid
- http://bio2rdf.org/drugbank_resource:Solution-Orale-D'acetaminophene-USP-En-Gouttes-80-mg/ml

I think the first and the third instance cause problems where using random TPF navigation over the DrugBank Graph, and should also cause problem for SPARQL querying I think. For example, the query: `SELECT DISTINCT ?Concept WHERE {[] a ?Concept}` shoots the error 
`Syntax error: unexpected "<http://bio2rdf.org/drugbank_resource:Ac\\uFFFD\\uFFFDtaminoph\\uFFFD\\uFFFDne-500-Mg-Comprime>" on line 316` using a TPF server-client system

**Comment by micheldumontier** [comment]
sure, sounds reasonable.  do you want to make modifications to the source code?

**Comment by maulikkamdar** [comment]
f1e2855
