### ISSUE TITLE
spaces in URIs and unescaped back slashes in the generated output for DRUGBANK

### ISSUE THREAD

**Issue by zaihrayeu** [bio2rdf/bio2rdf-scripts#447]
hi all,

I used the script to generate the DrugBank ontology from its sources, but I am facing difficulties with importing this ontology in GraphDB triple store that complains about spaces in URIs, e.g.:

http://bio2rdf.org/drugbank_vocabulary:x-therapeutic targets database

also, there are unescaped backward slashes as in:

drug\bank_all_full_data\base.xml.zip

has anyone faced this issue and/or knows how to fix it?

many thanks
Ilya

**Comment by micheldumontier** [comment]
Hi Ilya,
  can you tell me which source data file you used, and what you mean by "generate drugbank ontology"?

**Comment by zaihrayeu** [comment]
hi Michel,

I used the latest dump file from here: https://www.drugbank.ca/releases/latest

I had to modify the script a bit to read drug bank data from this file as otherwise it would try to download the source files from a location that does not seem to exist any more. the file can be downloaded also from here: https://drive.google.com/open?id=0B50dpR43NcFCM1NjeFlyRi1ibFE

by "generate drugbank ontology" I meant running the Bio2RDF parser script that generated two .nq files. the generated files can be downloaded from here: https://drive.google.com/open?id=0B50dpR43NcFCTG1aYnpnRW5BN28

**Comment by zaihrayeu** [comment]
hi Michael, I was wondering if you had a chance to give this issue a look? please let me know if I can provide any additional context

**Comment by micheldumontier** [comment]
Hi, as much as I'd like to address this issue, i won't be able able to until March. New resources are being recruited to the Bio2RDF project, but won't be in place for some time yet. If you can find a solution, i would very much appreciate it.
