### ISSUE TITLE
backslash characters in clinicaltrials

### ISSUE THREAD

**Issue by micheldumontier** [bio2rdf/bio2rdf-scripts#453]
Hi everyone,

I was trying to extend the ClinicalTrials.gov bio2rdf conversion script (see https://github.com/jvsoest/bio2rdf-scripts/commit/ce09d8386f71f8a6c7b18f78ee0699e53133de23), and test it before creating a pull request.

Generation of triples runs fine, and creates the clinicaltrials.nq.gz file. However some URIs in this file are containing strange backslash characters at random locations (see example below, "clnicaltrials_voca\bulary").

Does anyone know what could cause this issue?

Thanks in advance!

Kind regards,
Johan

Example:
<http://bio2rdf.org/clinicaltrials_vocabulary:Clinical-Study> <http://bio2rdf.org/bio2rdf_vocabulary:namespace> "clinicaltrials_voca\bulary"^^<http://www.w3.org/2001/XMLSchema#string> <http://bio2rdf.org/clinicaltrials_resource:bio2rdf.dataset.clinicaltrials.R4> .

**Comment by micheldumontier** [comment]
what platform are you using? can you share a (smallish) generated file?

**Comment by jvsoest** [comment]
Hi Michel,

I'm trying this on Ubuntu 16.04, with PHP version 7.0.15.
I've attached the conversion for one trial, where it sometimes escapes the "b" character.
 [clinicaltrials.nq.gz](https://github.com/bio2rdf/bio2rdf-scripts/files/1003410/clinicaltrials.nq.gz)

Maybe it's in the specialEscape function of rdfapi, I'll give it a try as well.

Regards,
Johan

**Comment by jvsoest** [comment]
As suspected, specialEscape and safeLiteral in rdfapi.php did the trick for me (currently). I've removed "\b" (first two characters) from the [addcslashes](http://php.net/manual/en/function.addcslashes.php) function. I think it handles the b as a character, instead of \b as backspace. But I'm not sure if this creates problems for other bio2rdf scripts.

**Comment by micheldumontier** [comment]
ok, i replaced the string definition with a hex list. see https://github.com/micheldumontier/php-lib/commit/252b8ef89589884547e3abf50a34d1252ece1ff2
