### ISSUE TITLE
Drugbank drug-target interactions

### ISSUE THREAD

**Issue by DuZhenzhen399** [bio2rdf/bio2rdf-scripts#461]
Interesting work!But some links are invalid,such as "drugbank.xml.zip" in folder "drugbank",I did not find it.Please check it.Thank you  so much.

**Comment by micheldumontier** [comment]
DrugBank now requires you to login from their website to gain access to the downloads. So you will have to get an account, download the file, and place it in the directory.

**Comment by DuZhenzhen399** [comment]
Thank you.And how about the file of’drugbank.nq.gz’?How can I download it?



发自我的iPhone


------------------ Original ------------------

**Comment by micheldumontier** [comment]
what do you mean? that file will be generated by running the runparser script for drugbank

**Comment by DuZhenzhen399** [comment]
> what do you mean? that file will be generated by running the runparser script for drugbank

Oh,I see.Anothor question is that when I get the RDF of drugbank,how can I got the relations/triples between drug and target?I want to study something about drug-target interaction predictions.
