### ISSUE TITLE
How can I parse the Drugbank.nq.gz?

### ISSUE THREAD

**Issue by DuZhenzhen399** [bio2rdf/bio2rdf-scripts#465]
I have generated the rdf file named"Drugban.nq.gz" by running the code ,but I do not know how to parse it,can you give me some advice.Thank you.

**Comment by Zhangs996** [comment]
试运行mesh.php得到了.nq.gz文件。
但是drugbank现在要账号批准后才能下载，关于drugbank_all_full_datasets.xml.zip您的路径写的是什么呢？是先把这个文件下载下来然后再进行解析吗，那么这一步是怎么操作的呢？望回复，谢谢-643396092@qq.com

**Comment by hangang96** [comment]
I encountered the same issue, how could I solve this?  thx
