### ISSUE TITLE
Inquiry about using bio2rdf to parse drugbank

### ISSUE THREAD

**Issue by yq-leo** [bio2rdf/bio2rdf-scripts#480]
Hi, I'm currently trying to parse drugbank and convert it to RDF using bio2rdf. I followed the developers' guide in the Wiki to set up the environment and ran runparser.php but it gave me an error: 'Fatal error: Uncaught ArgumentCountError: Too few arguments to function error_handler(), 4 passed and exactly 5 expected.' Also, I have drugbank_all_full_database.xml.zip stored in data/download and ran drugbank.php, but the program returned immediately without doing anything. I wonder what's wrong.

**Comment by micheldumontier** [comment]
Hi, sorry this project is no longer active.
